### ISSUE TITLE
main

### ISSUE THREAD

**Issue by hwijinl** [Lim-09/Lim-09#1]
![다운로드](https://github.com/Lim-09/Lim-09/assets/39161411/6122414e-b435-4ad7-824d-757a48ae8dd5)

**Comment by Lim-09** [comment]
![다운로드 (2)](https://github.com/Lim-09/Lim-09/assets/39161411/1f9e1eb5-6117-4338-bc3a-97228020233e)

**Comment by Lim-09** [comment]
![다운로드__2_-removebg-preview](https://github.com/Lim-09/Lim-09/assets/39161411/ebbbc0bd-7880-4deb-8f72-eee17325c7db)

**Comment by Lim-09** [comment]
![다운로드__2_-removebg-preview](https://github.com/Lim-09/Lim-09/assets/39161411/459a1178-8fbf-40d7-b4f6-57eccd70ff3d)

**Comment by hwijinl** [comment]
![다운로드-removebg-preview (1)](https://github.com/Lim-09/Lim-09/assets/39161411/5610001f-31a9-4476-8b6d-47304d04a2c3)
